-- Dolencias de biodescodificación basadas en Eric Corbera
-- Total: 30 dolencias completas
-- Ejecutar este script en Supabase SQL Editor

-- Limpiar tabla primero (opcional)
DELETE FROM dolencias WHERE categoria != 'SISTEMA_PLACEHOLDER';

INSERT INTO dolencias (nombre, descripcion, categoria, palabras_clave) VALUES
  ('Dolor de cabeza', 'Conflicto de desvalorización intelectual. Miedo a no estar a la altura intelectualmente. Presión mental excesiva por querer controlar todo. La cabeza representa nuestro yo consciente y el control.', 'Sistema nervioso', ARRAY['cabeza','migraña','cefalea','tensión','estrés','control','intelectual']),
  ('Asma', 'Sensación de asfixia en el territorio. Miedo a tomar su lugar en la vida. Conflicto con la madre o figura materna. Necesidad de espacio vital. Dificultad para expresar emociones.', 'Sistema respiratorio', ARRAY['respiración','ahogo','bronquios','pulmones','aire','territorio','madre']),
  ('Gastritis', 'Rabia contenida que no se puede expresar. Algo que no se puede ''digerir'' emocionalmente. Cólera en el territorio familiar o laboral. Injusticia no asimilada.', 'Sistema digestivo', ARRAY['estómago','acidez','digestión','rabia','injusticia','cólera']),
  ('Dolor de espalda', 'Sentimiento de no sentirse apoyado por la familia o entorno. Carga excesiva de responsabilidades. Miedo al futuro. Desvalorización de uno mismo.', 'Sistema musculoesquelético', ARRAY['espalda','columna','apoyo','responsabilidad','carga','futuro']),
  ('Insomnio', 'Culpabilidad por algo que se ha hecho o dejado de hacer. Miedo a perder el control. Hipervigilancia emocional. Necesidad de estar alerta ante el peligro.', 'Sistema nervioso', ARRAY['sueño','dormir','descanso','vigilia','control','culpa']),
  ('Artritis', 'Rigidez mental y emocional. Crítica constante hacia uno mismo y hacia otros. Sensación de ser víctima. Resentimiento acumulado. Falta de flexibilidad ante los cambios.', 'Sistema musculoesquelético', ARRAY['articulaciones','rigidez','flexibilidad','crítica','resentimiento','víctima']),
  ('Hipertensión', 'Tensión emocional acumulada. Problemas no resueltos del pasado. Necesidad de control excesivo. Miedo a enfrentar conflictos. Presión por cumplir expectativas.', 'Sistema cardiovascular', ARRAY['presión','tensión','corazón','control','expectativas','conflictos']),
  ('Depresión', 'Cólera dirigida hacia uno mismo. Sentimiento de desesperanza. Pérdida de la razón de vivir. Separación de algo o alguien querido. Desconexión del propósito de vida.', 'Sistema emocional', ARRAY['tristeza','desesperanza','pérdida','propósito','separación','cólera']),
  ('Ansiedad', 'Miedo al futuro y a lo desconocido. Pérdida de control sobre las circunstancias. Anticipación de peligros imaginarios. Necesidad de control y seguridad.', 'Sistema emocional', ARRAY['miedo','futuro','control','seguridad','nervios','peligro']),
  ('Diabetes', 'Tristeza profunda por no poder disfrutar de la dulzura de la vida. Necesidad de control sobre el entorno. Resistencia a recibir amor. Amargura acumulada.', 'Sistema endocrino', ARRAY['azúcar','dulzura','control','amargura','resistencia','amor']),
  ('Dolor de rodillas', 'Miedo a avanzar en la vida. Rigidez ante los cambios. Problemas de humildad y orgullo. Dificultad para ''doblegarse'' ante las circunstancias. Conflicto con la autoridad.', 'Sistema musculoesquelético', ARRAY['rodillas','avanzar','humildad','orgullo','flexibilidad','autoridad']),
  ('Dolor de garganta', 'Dificultad para expresar lo que se siente. Palabras que no se pueden decir. Rabia contenida. Miedo al juicio de otros. Conflicto entre lo que se piensa y lo que se dice.', 'Sistema respiratorio', ARRAY['garganta','expresar','palabras','comunicación','juicio','silencio']),
  ('Cistitis', 'Conflicto de territorio. Enfado con la pareja. Marcaje del territorio emocional. Dificultades en las relaciones íntimas. Miedo a ser invadido emocionalmente.', 'Sistema urinario', ARRAY['cistitis','territorio','pareja','intimidad','invasión','enfado']),
  ('Sinusitis', 'Conflicto de olfato social. No soportar a alguien cercano. Situación que ''no se puede oler''. Irritación por la presencia de alguien. Rechazo a algo del entorno.', 'Sistema respiratorio', ARRAY['sinusitis','olfato','rechazo','irritación','presencia','entorno']),
  ('Eczema', 'Conflicto de separación. Pérdida de contacto con un ser querido. Necesidad de protección. Miedo al contacto físico o emocional. Separación dolorosa no resuelta.', 'Piel', ARRAY['eczema','separación','contacto','protección','pérdida','piel']),
  ('Dolor de hombros', 'Carga excesiva de responsabilidades. Sensación de llevar el peso del mundo. Dificultad para delegar. Falta de apoyo. Cargar con los problemas de otros.', 'Sistema musculoesquelético', ARRAY['hombros','responsabilidad','carga','peso','delegar','apoyo']),
  ('Otitis', 'Conflicto de no querer escuchar algo. Rabia por lo que se está oyendo. Información que molesta. Conflicto auditivo en el territorio. Rechazo a ciertas palabras o sonidos.', 'Oídos', ARRAY['otitis','escuchar','rabia','sonidos','información','rechazo']),
  ('Conjuntivitis', 'Conflicto de no querer ver algo. Situación visual molesta. Rechazo a lo que se está viendo. Cólera por algo que está frente a los ojos. Negación de la realidad.', 'Ojos', ARRAY['conjuntivitis','ver','visual','cólera','negación','realidad']),
  ('Herpes labial', 'Conflicto de beso no deseado o deseado pero no dado. Rechazo o deseo sexual reprimido. Conflicto entre lo que se quiere expresar y lo que está prohibido.', 'Piel', ARRAY['herpes','beso','rechazo','deseo','prohibido','expresión']),
  ('Colon irritable', 'Conflicto de guarrería o algo asqueroso que no se puede eliminar. Situación que molesta profundamente. Incapacidad para procesar y eliminar experiencias negativas.', 'Sistema digestivo', ARRAY['colon','irritable','eliminar','guarrería','procesar','negativo']),
  ('Fibromialgia', 'Conflicto de desvalorización extrema. Sentirse inútil e incapaz. Dolor emocional profundo que se somatiza en todo el cuerpo. Falta de reconocimiento y amor propio.', 'Sistema musculoesquelético', ARRAY['fibromialgia','desvalorización','inútil','dolor','reconocimiento','amor']),
  ('Cálculos renales', 'Conflicto de líquido. Situaciones que se cristalizan y endurecen. Emociones que se ''petrifican''. Dificultad para fluir con la vida. Rigidez emocional.', 'Sistema urinario', ARRAY['cálculos','renales','cristalizar','fluir','rigidez','emocional']),
  ('Alopecia', 'Conflicto de separación brutal del grupo. Pérdida de protección. Sensación de estar desprotegido. Separación traumática de la familia o clan. Pérdida de identidad.', 'Piel', ARRAY['alopecia','separación','protección','desprotegido','familia','identidad']),
  ('Vértigo', 'Conflicto de caída. Miedo a perder el control. Sensación de que la vida se tambalea. Conflicto entre lo que se quiere y lo que se debe hacer. Pérdida de referencias.', 'Oídos', ARRAY['vértigo','caída','control','tambalea','referencias','equilibrio']),
  ('Hipotiroidismo', 'Conflicto de tiempo y urgencia. Sensación de no llegar a tiempo. Desesperación por no poder alcanzar algo. Ralentización forzada para evitar el fracaso.', 'Sistema endocrino', ARRAY['hipotiroidismo','tiempo','urgencia','desesperación','ralentización','fracaso']),
  ('Cáncer de mama', 'Conflicto en el nido. Preocupación extrema por un hijo o ser querido. Sobreprotección. Conflicto de dar y recibir nutrición emocional. Drama en el hogar.', 'Sistema reproductivo', ARRAY['mama','nido','hijo','sobreprotección','nutrición','hogar']),
  ('Hemorroides', 'Conflicto de identidad en el territorio. No saber cuál es su lugar. Conflicto con la autoridad del territorio. Presión por mantenerse en una posición.', 'Sistema digestivo', ARRAY['hemorroides','identidad','territorio','lugar','autoridad','posición']),
  ('Lumbalgia', 'Conflicto de desvalorización en el movimiento. Miedo a avanzar. Falta de flexibilidad ante los cambios. Rigidez mental que se refleja en la espalda baja.', 'Sistema musculoesquelético', ARRAY['lumbalgia','movimiento','avanzar','flexibilidad','cambios','rigidez']),
  ('Acné', 'Conflicto de imagen y aceptación. Rechazo a la propia imagen. Conflicto de seducción y atractivo. Miedo al juicio de otros sobre la apariencia física.', 'Piel', ARRAY['acné','imagen','aceptación','seducción','atractivo','apariencia']),
  ('Tinnitus', 'Conflicto auditivo interno. Necesidad obsesiva de escuchar algo. Ruido mental constante. Dificultad para encontrar silencio interior. Hipervigilancia auditiva.', 'Oídos', ARRAY['tinnitus','auditivo','ruido','silencio','hipervigilancia','interno']);

-- Verificar inserción
SELECT COUNT(*) as total_dolencias FROM dolencias;
SELECT categoria, COUNT(*) as cantidad FROM dolencias GROUP BY categoria ORDER BY cantidad DESC;
